from login import *
from PyQt5.QtWidgets import QMessageBox
from PyQt5 import QtCore, QtGui, QtWidgets


class Register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 760)
        MainWindow.setStyleSheet("background: white;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 200, 301, 61))
        self.label.setObjectName("label")
        self.gender = QtWidgets.QComboBox(self.centralwidget)
        self.gender.setGeometry(QtCore.QRect(140, 470, 241, 41))
        self.gender.setObjectName("gender")
        self.gender.addItem("")
        self.gender.addItem("")
        self.time = QtWidgets.QComboBox(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(140, 550, 241, 41))
        self.time.setObjectName("time")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.time.addItem("")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(720, 230, 211, 211))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(50, 80, 101, 31))
        self.label_8.setObjectName("label_8")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(-130, 10, 1091, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(700, 20, 371, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(720, 50, 351, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(730, 70, 341, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(760, 90, 311, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(760, 110, 311, 20))
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(140, 10, 351, 151))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("Screenshot from 2020-01-28 13-55-45.png"))
        self.label_15.setScaledContents(False)
        self.label_15.setObjectName("label_15")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 210, 61, 61))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 310, 111, 51))
        self.label_9.setObjectName("label_9")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(140, 310, 411, 51))
        self.name.setStyleSheet("font: bold;\n"
"font-size: 20px;\n"
"")
        self.name.setText("")
        self.name.setObjectName("name")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 390, 111, 51))
        self.label_10.setObjectName("label_10")
        self.address = QtWidgets.QLineEdit(self.centralwidget)
        self.address.setGeometry(QtCore.QRect(140, 390, 411, 51))
        self.address.setStyleSheet("\n"
"font: bold;\n"
"font-size: 20px;\n"
"")
        self.address.setObjectName("address")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 470, 121, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 550, 81, 41))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(440, 550, 131, 41))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(430, 470, 211, 41))
        self.label_14.setObjectName("label_14")
        self.status = QtWidgets.QComboBox(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(640, 470, 241, 41))
        self.status.setStyleSheet("")
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.addItem("")
        self.duration = QtWidgets.QComboBox(self.centralwidget)
        self.duration.setGeometry(QtCore.QRect(640, 550, 241, 41))
        self.duration.setObjectName("duration")
        self.duration.addItem("")
        self.duration.addItem("")
        self.duration.addItem("")
        self.duration.addItem("")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(310, 660, 291, 51))
        self.save.setStyleSheet("font: bold;\n"
"font-size: 20px;\n"
"color: black;\n"
"background-color: white;")
        self.save.setObjectName("save")
        
        ####
        
        self.save.clicked.connect(self.popup)
        ####
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(810, 670, 141, 41))
        self.exit.setStyleSheet("font: bold;\n"
"font-size: 20px;\n"
"color: black;")
        icon = QtGui.QIcon.fromTheme("exit")
        self.exit.setIcon(icon)
        self.exit.setObjectName("exit")
        
        ###
        self.exit.clicked.connect(self.exits)
        ###
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(510, 220, 201, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 240, 281, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionADMIN = QtWidgets.QAction(MainWindow)
        self.actionADMIN.setObjectName("actionADMIN")
        self.actionREGISTERED_STUDENTS = QtWidgets.QAction(MainWindow)
        self.actionREGISTERED_STUDENTS.setObjectName("actionREGISTERED_STUDENTS")
        self.actionSTATISTICS = QtWidgets.QAction(MainWindow)
        self.actionSTATISTICS.setObjectName("actionSTATISTICS")
        self.actionLOGOUT = QtWidgets.QAction(MainWindow)
        self.actionLOGOUT.setObjectName("actionLOGOUT")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
###############################################################################################################################

    def enterData(self):
        name = self.name.text()
        address = self.address.text()
        gender = self.gender.currentText()
        time = self.time.currentText()
        status = self.status.currentText()
        duration = self.duration.currentText()
        date = self.lineEdit.text()

        conn = sqlite3.connect("midway.db")
        cur = conn.cursor()

        cur.execute("INSERT INTO registration VALUES(?,?,?,?,?,?,?)",(name,address,gender,status,duration,time,date))

        conn.commit()

        conn.close()

##############################################################################################################################
    def popup(self):
        self.enterData()
        msg = QMessageBox()
        msg.setWindowTitle("Alert")
        msg.setText("New Student Registered Successfully!")
        msg.setIcon(QMessageBox.Information)
        
        x = msg.exec_()
        
    def exits(self):
        exit()
        
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MIDWAY DRIVING SCHOOL 2020"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">REGISTRATION FORM</span></p></body></html>"))
        self.gender.setItemText(0, _translate("MainWindow", "MALE"))
        self.gender.setItemText(1, _translate("MainWindow", "FEMALE"))
        self.time.setItemText(0, _translate("MainWindow", "9AM"))
        self.time.setItemText(1, _translate("MainWindow", "10AM"))
        self.time.setItemText(2, _translate("MainWindow", "11AM"))
        self.time.setItemText(3, _translate("MainWindow", "12PM"))
        self.time.setItemText(4, _translate("MainWindow", "1PM"))
        self.time.setItemText(5, _translate("MainWindow", "2PM"))
        self.time.setItemText(6, _translate("MainWindow", "3PM"))
        self.time.setItemText(7, _translate("MainWindow", "4PM"))
        self.time.setItemText(8, _translate("MainWindow", "5PM"))
        self.time.setItemText(9, _translate("MainWindow", "6PM"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">PHOTO</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:20pt; font-weight:600;\">MIDWAY DRIVING SCHOOL</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Address: Manjai, The Gambia</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Tel: (+220 ) 3918800 / 793 3540</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">Facebook: midwaydrivingschool gambia</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600;\">E-mail: midwaydrivingschool3@gmail.com</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Date</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Name  </span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Address  </span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Gender  </span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Time  </span></p></body></html>"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Duration </span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">Marital Status  </span></p></body></html>"))
        self.status.setItemText(0, _translate("MainWindow", "SINGLE"))
        self.status.setItemText(1, _translate("MainWindow", "MARRIED"))
        self.duration.setItemText(0, _translate("MainWindow", "ONE WEEKS"))
        self.duration.setItemText(1, _translate("MainWindow", "TWO WEEKS"))
        self.duration.setItemText(2, _translate("MainWindow", "THREE WEEKS"))
        self.duration.setItemText(3, _translate("MainWindow", "ONE MONTH"))
        self.save.setText(_translate("MainWindow", "REGISTER NEW STUDENT"))
        self.exit.setText(_translate("MainWindow", "QUIT"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "10/feb/2020"))
        self.actionADMIN.setText(_translate("MainWindow", "ADMIN"))
        self.actionREGISTERED_STUDENTS.setText(_translate("MainWindow", "REGISTERED STUDENTS"))
        self.actionSTATISTICS.setText(_translate("MainWindow", "STATISTICS"))
        self.actionLOGOUT.setText(_translate("MainWindow", "LOGOUT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Register()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
